"""Movement opportunity engine contracts.

Movement candidates are proposals only. They do not place orders, call broker
APIs, or mutate execution state.
"""

from movement_engine.candidate_pool import (
    HARD_POOL_BLOCKERS,
    CandidatePoolResult,
    CandidatePoolSummary,
    build_candidate_pool,
)
from movement_engine.context import StrategyContext
from movement_engine.contract import (
    CandidateStatus,
    Direction,
    MovementCandidateValidationResult,
    StrategyCandidate,
    candidate_from_mapping,
    validate_strategy_candidate,
)
from movement_engine.no_trade_filter import (
    HARD_NO_TRADE_BLOCKERS,
    NO_TRADE_FILTER_EVIDENCE_KEY,
    NoTradeDecision,
    NoTradeFilterBatchResult,
    NoTradeFilterResult,
    NoTradeFilterSummary,
    apply_no_trade_filter,
    apply_no_trade_filter_to_candidates,
)
from movement_engine.option_pressure import (
    OPTION_PRESSURE_EVIDENCE_KEY,
    OptionPressureConfirmationResult,
    OptionPressureStatus,
    attach_option_pressure_confirmation,
    attach_option_pressure_to_candidates,
    confirm_option_pressure,
)
from movement_engine.pipeline import (
    PIPELINE_SCHEMA_VERSION,
    MovementOpportunityPipelineResult,
    MovementOpportunityPipelineSummary,
    build_default_movement_registry,
    run_movement_opportunity_pipeline,
)
from movement_engine.providers import (
    COMPRESSION_BREAKOUT_PROVIDER_ID,
    FAILED_BREAKOUT_TRAP_PROVIDER_ID,
    OPENING_DRIVE_PROVIDER_ID,
    ORB_RETEST_PROVIDER_ID,
    TREND_PULLBACK_PROVIDER_ID,
    VWAP_RECLAIM_PROVIDER_ID,
    build_compression_trend_candidate_pool,
    build_vwap_trap_candidate_pool,
    compression_breakout_provider,
    failed_breakout_trap_provider,
    opening_drive_provider,
    orb_retest_provider,
    register_compression_trend_providers,
    register_opening_drive_orb_providers,
    register_vwap_trap_providers,
    trend_pullback_provider,
    vwap_reclaim_provider,
)
from movement_engine.providers.opening_drive_orb import build_opening_drive_orb_candidate_pool
from movement_engine.ranker import (
    RANKER_EVIDENCE_KEY,
    CandidateRankExclusion,
    CandidateRankRecord,
    MovementRankResult,
    MovementRankSummary,
    RankExclusionReason,
    rank_movement_candidates,
)
from movement_engine.regime import (
    MovementRegime,
    MovementRegimeResult,
    classify_movement_regime,
)
from movement_engine.registry import (
    MovementProviderRegistrationResult,
    MovementRegistryRunResult,
    MovementStrategyProvider,
    MovementStrategyRegistry,
)

__all__ = [
    "COMPRESSION_BREAKOUT_PROVIDER_ID",
    "CandidatePoolResult",
    "CandidatePoolSummary",
    "CandidateRankExclusion",
    "CandidateRankRecord",
    "CandidateStatus",
    "Direction",
    "FAILED_BREAKOUT_TRAP_PROVIDER_ID",
    "HARD_NO_TRADE_BLOCKERS",
    "HARD_POOL_BLOCKERS",
    "MovementCandidateValidationResult",
    "MovementOpportunityPipelineResult",
    "MovementOpportunityPipelineSummary",
    "MovementProviderRegistrationResult",
    "MovementRankResult",
    "MovementRankSummary",
    "MovementRegime",
    "MovementRegimeResult",
    "MovementRegistryRunResult",
    "MovementStrategyProvider",
    "MovementStrategyRegistry",
    "NO_TRADE_FILTER_EVIDENCE_KEY",
    "NoTradeDecision",
    "NoTradeFilterBatchResult",
    "NoTradeFilterResult",
    "NoTradeFilterSummary",
    "OPENING_DRIVE_PROVIDER_ID",
    "OPTION_PRESSURE_EVIDENCE_KEY",
    "ORB_RETEST_PROVIDER_ID",
    "OptionPressureConfirmationResult",
    "OptionPressureStatus",
    "PIPELINE_SCHEMA_VERSION",
    "RANKER_EVIDENCE_KEY",
    "RankExclusionReason",
    "StrategyCandidate",
    "StrategyContext",
    "TREND_PULLBACK_PROVIDER_ID",
    "VWAP_RECLAIM_PROVIDER_ID",
    "apply_no_trade_filter",
    "apply_no_trade_filter_to_candidates",
    "attach_option_pressure_confirmation",
    "attach_option_pressure_to_candidates",
    "build_candidate_pool",
    "build_compression_trend_candidate_pool",
    "build_default_movement_registry",
    "build_opening_drive_orb_candidate_pool",
    "build_vwap_trap_candidate_pool",
    "candidate_from_mapping",
    "classify_movement_regime",
    "compression_breakout_provider",
    "confirm_option_pressure",
    "failed_breakout_trap_provider",
    "opening_drive_provider",
    "orb_retest_provider",
    "rank_movement_candidates",
    "register_compression_trend_providers",
    "register_opening_drive_orb_providers",
    "register_vwap_trap_providers",
    "run_movement_opportunity_pipeline",
    "trend_pullback_provider",
    "validate_strategy_candidate",
    "vwap_reclaim_provider",
]
