"""Paper trading contracts for Algotradify.

This package builds simulation-only paper intent, lifecycle, fill, position, MTM,
realized PnL, slippage, performance snapshot, canonical paper event journal,
deterministic paper state rebuild evidence, paper state reconciliation reports,
in-memory paper trading pipeline evidence, local paper evidence persistence,
non-destructive paper session boundary controls, deterministic paper scenario
suite evidence, and local paper evidence export bundles. It does not place
broker orders and does not expose real order actions.
"""

from paper_trading.event_journal import (
    PaperEventJournalResult,
    append_paper_event,
    load_paper_events,
    paper_event_journal_schema_contract,
)
from paper_trading.events import (
    PaperEvent,
    PaperEventType,
    normalize_paper_event,
    paper_event_schema_contract,
    validate_paper_event,
)
from paper_trading.export_bundle import (
    PaperExportBundleResult,
    PaperExportBundleStatus,
    build_paper_export_bundle,
    load_paper_export_manifest,
    paper_export_bundle_schema_contract,
    stable_file_hash,
    validate_paper_export_bundle,
)
from paper_trading.fill_simulation import (
    PaperFillSimulationResult,
    PaperFillSimulationStatus,
    paper_fill_simulation_schema_contract,
    simulate_paper_fill,
    validate_paper_fill_simulation_inputs,
)
from paper_trading.intent_bridge import (
    PaperOrderIntent,
    PaperOrderIntentResult,
    build_paper_order_intent,
    paper_order_intent_schema_contract,
    validate_paper_order_intent,
)
from paper_trading.lifecycle import (
    PaperOrderLifecycleEvent,
    PaperOrderLifecycleResult,
    PaperOrderLifecycleStatus,
    build_paper_order_lifecycle_event,
    paper_order_lifecycle_schema_contract,
    validate_paper_order_lifecycle_transition,
)
from paper_trading.mtm_pnl import (
    PaperMtmPnlResult,
    PaperMtmPnlStatus,
    build_paper_mtm_pnl,
    paper_mtm_pnl_schema_contract,
    validate_paper_mtm_pnl_inputs,
)
from paper_trading.performance_snapshot import (
    PaperPerformanceSnapshotResult,
    PaperPerformanceSnapshotStatus,
    build_paper_performance_snapshot,
    paper_performance_snapshot_schema_contract,
    validate_paper_performance_snapshot_inputs,
)
from paper_trading.persistence import (
    PaperEvidencePersistenceStatus,
    PaperEvidenceReadResult,
    PaperEvidenceRecord,
    PaperEvidenceWriteResult,
    load_paper_evidence_records,
    paper_evidence_persistence_schema_contract,
    stable_paper_evidence_payload_hash,
    validate_paper_evidence_record,
    validate_paper_evidence_write_inputs,
    write_paper_evidence_record,
)
from paper_trading.pipeline import (
    PaperTradingPipelineResult,
    PaperTradingPipelineStatus,
    paper_trading_pipeline_schema_contract,
    run_paper_trading_pipeline,
    validate_paper_trading_pipeline_inputs,
)
from paper_trading.position_ledger import (
    PaperPositionLedgerResult,
    PaperPositionLedgerStatus,
    build_paper_position_ledger,
    paper_position_ledger_schema_contract,
    validate_paper_position_ledger_inputs,
)
from paper_trading.realized_pnl import (
    PaperRealizedPnlResult,
    PaperRealizedPnlStatus,
    build_paper_realized_pnl,
    paper_realized_pnl_schema_contract,
    validate_paper_realized_pnl_inputs,
)
from paper_trading.rebuild import (
    PaperJournalRebuildResult,
    PaperJournalRebuildStatus,
    paper_journal_rebuild_schema_contract,
    rebuild_paper_journal,
    validate_paper_journal_rebuild_inputs,
)
from paper_trading.reconciliation import (
    PaperStateReconciliationResult,
    PaperStateReconciliationStatus,
    paper_state_reconciliation_schema_contract,
    reconcile_paper_state,
    validate_paper_state_reconciliation_inputs,
)
from paper_trading.scenarios import (
    PaperScenarioName,
    PaperScenarioResult,
    PaperScenarioStatus,
    paper_scenario_schema_contract,
    run_paper_scenario,
    run_standard_paper_scenarios,
    validate_paper_scenario_inputs,
)
from paper_trading.session_boundary import (
    PAPER_SESSION_BOUNDARY_RECORD_TYPE,
    PaperSessionBoundaryResult,
    PaperSessionBoundaryStatus,
    PaperSessionBoundaryType,
    build_paper_session_boundary_record,
    build_paper_session_id,
    load_paper_session_boundaries,
    mark_paper_session_boundary,
    paper_session_boundary_schema_contract,
    validate_paper_session_boundary_record,
)
from paper_trading.slippage import (
    PaperSlippageResult,
    PaperSlippageStatus,
    build_paper_slippage_report,
    paper_slippage_schema_contract,
    validate_paper_slippage_inputs,
)

__all__ = [
    "PaperEvent",
    "PaperEventType",
    "PaperEventJournalResult",
    "append_paper_event",
    "load_paper_events",
    "normalize_paper_event",
    "paper_event_schema_contract",
    "paper_event_journal_schema_contract",
    "validate_paper_event",
    "PaperExportBundleResult",
    "PaperExportBundleStatus",
    "build_paper_export_bundle",
    "load_paper_export_manifest",
    "paper_export_bundle_schema_contract",
    "stable_file_hash",
    "validate_paper_export_bundle",
    "PaperOrderIntent",
    "PaperOrderIntentResult",
    "build_paper_order_intent",
    "paper_order_intent_schema_contract",
    "validate_paper_order_intent",
    "PaperOrderLifecycleEvent",
    "PaperOrderLifecycleResult",
    "PaperOrderLifecycleStatus",
    "build_paper_order_lifecycle_event",
    "paper_order_lifecycle_schema_contract",
    "validate_paper_order_lifecycle_transition",
    "PaperFillSimulationResult",
    "PaperFillSimulationStatus",
    "paper_fill_simulation_schema_contract",
    "simulate_paper_fill",
    "validate_paper_fill_simulation_inputs",
    "PaperPositionLedgerResult",
    "PaperPositionLedgerStatus",
    "build_paper_position_ledger",
    "paper_position_ledger_schema_contract",
    "validate_paper_position_ledger_inputs",
    "PaperMtmPnlResult",
    "PaperMtmPnlStatus",
    "build_paper_mtm_pnl",
    "paper_mtm_pnl_schema_contract",
    "validate_paper_mtm_pnl_inputs",
    "PaperRealizedPnlResult",
    "PaperRealizedPnlStatus",
    "build_paper_realized_pnl",
    "paper_realized_pnl_schema_contract",
    "validate_paper_realized_pnl_inputs",
    "PaperSlippageResult",
    "PaperSlippageStatus",
    "build_paper_slippage_report",
    "paper_slippage_schema_contract",
    "validate_paper_slippage_inputs",
    "PaperPerformanceSnapshotResult",
    "PaperPerformanceSnapshotStatus",
    "build_paper_performance_snapshot",
    "paper_performance_snapshot_schema_contract",
    "validate_paper_performance_snapshot_inputs",
    "PaperJournalRebuildResult",
    "PaperJournalRebuildStatus",
    "paper_journal_rebuild_schema_contract",
    "rebuild_paper_journal",
    "validate_paper_journal_rebuild_inputs",
    "PaperStateReconciliationResult",
    "PaperStateReconciliationStatus",
    "paper_state_reconciliation_schema_contract",
    "reconcile_paper_state",
    "validate_paper_state_reconciliation_inputs",
    "PaperTradingPipelineResult",
    "PaperTradingPipelineStatus",
    "paper_trading_pipeline_schema_contract",
    "run_paper_trading_pipeline",
    "validate_paper_trading_pipeline_inputs",
    "PaperEvidencePersistenceStatus",
    "PaperEvidenceReadResult",
    "PaperEvidenceRecord",
    "PaperEvidenceWriteResult",
    "load_paper_evidence_records",
    "paper_evidence_persistence_schema_contract",
    "stable_paper_evidence_payload_hash",
    "validate_paper_evidence_record",
    "validate_paper_evidence_write_inputs",
    "write_paper_evidence_record",
    "PAPER_SESSION_BOUNDARY_RECORD_TYPE",
    "PaperSessionBoundaryResult",
    "PaperSessionBoundaryStatus",
    "PaperSessionBoundaryType",
    "build_paper_session_boundary_record",
    "build_paper_session_id",
    "load_paper_session_boundaries",
    "mark_paper_session_boundary",
    "paper_session_boundary_schema_contract",
    "validate_paper_session_boundary_record",
    "PaperScenarioName",
    "PaperScenarioResult",
    "PaperScenarioStatus",
    "paper_scenario_schema_contract",
    "run_paper_scenario",
    "run_standard_paper_scenarios",
    "validate_paper_scenario_inputs",
]
