"""Agent intake foundation contracts, guards, approval, evidence, local task storage, and governance.

This package is intentionally isolated from API, dashboard, broker, live, and paper-trading
runtime code. Agent governance contracts remain non-executing and patch-review oriented.
"""

from agent_system.approval import (
    AgentApprovalDecision,
    agent_approval_schema_contract,
    approve_agent_work,
)
from agent_system.evidence import (
    AgentEvidenceError,
    agent_evidence_schema_contract,
    build_agent_evidence_payload,
    write_agent_evidence,
)
from agent_system.patch_approval import (
    AGENT_PATCH_APPROVAL_CONTRACT,
    AGENT_PATCH_APPROVAL_SCHEMA_VERSION,
    AgentPatchApprovalError,
    agent_patch_approval_schema_contract,
    build_agent_patch_approval_record,
    build_agent_patch_rejection_record,
    load_agent_patch_approval,
    persist_agent_patch_approval,
)
from agent_system.role_registry import (
    AGENT_ROLE_REGISTRY_CONTRACT,
    FORBIDDEN_ROLE_ACTIONS,
    FORBIDDEN_ROLE_PATH_PREFIXES,
    HIGH_RISK_ROLE_PATH_PREFIXES,
    SAFE_ROLE_FLAGS,
    AgentRole,
    AgentRoleContract,
    agent_role_registry_schema_contract,
    assess_role_request,
    build_agent_role_registry,
    get_agent_role_contract,
    validate_agent_role_registry,
)
from agent_system.scope_guard import (
    FORBIDDEN_PATH_PREFIXES,
    HIGH_RISK_PATH_PREFIXES,
    LOW_RISK_PATH_PREFIXES,
    SOURCE_ALLOWED_ACTIONS,
    AgentScopeDecision,
    agent_scope_guard_schema_contract,
    assess_agent_scope,
)
from agent_system.task_store import (
    TASK_STORE_SCHEMA_VERSION,
    AgentTaskRecord,
    AgentTaskStoreError,
    agent_task_store_schema_contract,
    build_agent_task_record,
    load_agent_task,
    persist_agent_task,
    query_agent_tasks,
    rebuild_agent_task_index,
)
from agent_system.workflow_state import (
    AGENT_WORKFLOW_STATE_CONTRACT,
    ORDERED_ACTIVE_STATES,
    ROLE_REQUIRED_TRANSITIONS,
    TERMINAL_BLOCKED_STATES,
    AgentWorkflowDecision,
    AgentWorkflowState,
    agent_workflow_state_schema_contract,
    evaluate_agent_workflow_transition,
    replay_agent_workflow,
    validate_agent_workflow_state_machine,
)
from agent_system.work_contract import (
    AGENT_WORK_SCHEMA_VERSION,
    FORBIDDEN_AGENT_ACTIONS,
    SAFE_AGENT_ACTIONS,
    AgentAction,
    AgentRiskLevel,
    AgentSource,
    AgentWorkRequest,
    AgentWorkValidationError,
    agent_work_schema_contract,
    build_agent_work_id,
    normalize_agent_work_request,
)

__all__ = [
    "AGENT_PATCH_APPROVAL_CONTRACT",
    "AGENT_PATCH_APPROVAL_SCHEMA_VERSION",
    "AGENT_ROLE_REGISTRY_CONTRACT",
    "AGENT_WORKFLOW_STATE_CONTRACT",
    "AGENT_WORK_SCHEMA_VERSION",
    "FORBIDDEN_AGENT_ACTIONS",
    "FORBIDDEN_PATH_PREFIXES",
    "FORBIDDEN_ROLE_ACTIONS",
    "FORBIDDEN_ROLE_PATH_PREFIXES",
    "HIGH_RISK_PATH_PREFIXES",
    "HIGH_RISK_ROLE_PATH_PREFIXES",
    "LOW_RISK_PATH_PREFIXES",
    "ORDERED_ACTIVE_STATES",
    "ROLE_REQUIRED_TRANSITIONS",
    "SAFE_AGENT_ACTIONS",
    "SAFE_ROLE_FLAGS",
    "SOURCE_ALLOWED_ACTIONS",
    "TASK_STORE_SCHEMA_VERSION",
    "TERMINAL_BLOCKED_STATES",
    "AgentAction",
    "AgentApprovalDecision",
    "AgentEvidenceError",
    "AgentPatchApprovalError",
    "AgentRiskLevel",
    "AgentRole",
    "AgentRoleContract",
    "AgentScopeDecision",
    "AgentSource",
    "AgentTaskRecord",
    "AgentTaskStoreError",
    "AgentWorkflowDecision",
    "AgentWorkflowState",
    "AgentWorkRequest",
    "AgentWorkValidationError",
    "agent_approval_schema_contract",
    "agent_evidence_schema_contract",
    "agent_patch_approval_schema_contract",
    "agent_role_registry_schema_contract",
    "agent_scope_guard_schema_contract",
    "agent_task_store_schema_contract",
    "agent_work_schema_contract",
    "agent_workflow_state_schema_contract",
    "approve_agent_work",
    "assess_agent_scope",
    "assess_role_request",
    "build_agent_evidence_payload",
    "build_agent_patch_approval_record",
    "build_agent_patch_rejection_record",
    "build_agent_role_registry",
    "build_agent_task_record",
    "build_agent_work_id",
    "evaluate_agent_workflow_transition",
    "get_agent_role_contract",
    "load_agent_patch_approval",
    "load_agent_task",
    "normalize_agent_work_request",
    "persist_agent_patch_approval",
    "persist_agent_task",
    "query_agent_tasks",
    "rebuild_agent_task_index",
    "replay_agent_workflow",
    "validate_agent_role_registry",
    "validate_agent_workflow_state_machine",
    "write_agent_evidence",
]
